{"name": "Test01: Log in to grafana using DB", "status": "broken", "statusDetails": {"message": "TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'", "trace": "request = <SubRequest 'init_driver' for <Function test_login_grafana>>\n\n    @pytest.fixture(scope='class')\n    def init_driver(request):\n>       edriver = get_driver()\n\ntest_cases\\conftest.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_cases\\conftest.py:118: in get_driver\n    driver = get_chrome()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def get_chrome():\n    \n        #chrome_driver = webdriver.Chrome(ChromeDriverManager().install())  #selenium 3.x\n        srv = Service(ChromeDriverManager().install())\n>       chrome_driver = selenium.webdriver.Chrome(service=srv)\nE       TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'\n\ntest_cases\\conftest.py:144: TypeError"}, "description": "Log in to grafana using DB", "start": 1726496777927, "stop": 1726496777927, "uuid": "f17ca82a-2e41-4405-ada0-5e1cf850dbfb", "historyId": "b831385f8be5373e2699aa37dbb05c32", "testCaseId": "b831385f8be5373e2699aa37dbb05c32", "fullName": "test_cases.test_cases_db.TestCasesDB#test_login_grafana", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_database_connection')"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_cases_db"}, {"name": "subSuite", "value": "TestCasesDB"}, {"name": "host", "value": "DESKTOP-1SRCFM0"}, {"name": "thread", "value": "19216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_cases_db"}]}